# From rules to floorplan

## 1. Import libraries

In [1]:
# importing NumPy and NetworkX for working with graphs
import numpy as np
import networkx as nx 

# importing topogenesis for working wiith lattices / regular-grids
import topogenesis as tg

# importing pyvista for visualizations
import pyvista as pv

# importing Pandas and display for clearer representation of table data and matrices
import pandas as pd
from IPython.display import display

## 2.1 Define grid size

In [2]:
# Define the grid 
len_vertical = 14
len_horizontal = 24

## 2.2 Define map

In [3]:
# Functions:
"""
functions =
{ 
    0 : "empty",
    1 : "water",
    2 : "road",
    3 : "souk"
    4 : "water workshop",
    5 : "helofytenfitler",
    6 : "square",
    7 : "non-water workshop",
    8 : "shop",
    9 : "house",
}
"""

# Water canal as manual input
water = [
    (0, 13),
    (1, 13),
    (2, 13),
    (3, 13),
    (4, 13),

    (4, 12),
    (4, 11),
    (4, 10),
    (4, 9),
    (4, 8),
    (4, 7),
    (4, 6),

    (5, 6),
    (6, 6),
    (7, 6),
    (8, 6),
    (9, 6),
    (10, 6),
    (11, 6),
    (12, 6),
    (13, 6),

    (10, 6),
    (10, 7),
    (10, 8),
    (10, 9),
    (10, 10),
    (10, 11),
    (10, 12),
    (10, 13),
    (10, 14),
    (10, 15),
    (10, 16),
    (10, 17),
    (10, 18),
    (10, 19),
    (10, 20),
    (10, 21),
    (10, 22),
    (10, 23),

]


## 2.3 Place canal on the map

In [4]:
# VV is a matrix with this shape: number of nodes by number of nodes
len_grid = len_vertical, len_horizontal
# Initialize the empty VV
grid = np.zeros(len_grid, dtype=int)

# iterate over the egdes
for n1, n2 in water:
    # since the graph is undrirected we fill the matrix 
    # on both side of the diagonal line
    grid[n1, n2] = 1

# display as pandas dataframe
map_display = display(pd.DataFrame(grid))
map_display

0   1   2   3   4   5   6   7   8   9   ...  14  15  16  17  18  19  20  \
0    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
4    0   0   0   0   0   0   1   1   1   1  ...   0   0   0   0   0   0   0   
5    0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   
6    0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   
7    0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   
8    0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   
9    0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   
10   0   0   0   0   0   0   1   1   1   1  ...   1   1   1   1   1   1   1   
11   0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   
12   0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   
13   0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   

    21  22  23  
0    0   0   0  
1    0   0   0  
2    0   0   0  
3    0   0   0  
4    0   0   0  
5    0   0   0  
6    0   0   0  
7    0   0   0  
8    0   0   0  
9    0   0   0  
10   1   1   1  
11   0   0   0  
12   0   0   0  
13   0   0   0  

[14 rows x 24 columns]

## 3. Rules to floorplan

1. Locate the underground waterstorage
2. Lay one main road vertically and one horizontally along the water storage, as central as possible
3. connect smaller roads to the main road, evenly spaced. start with roads along the river
4. the workshops that need water go on top of the water storage, along a (main/small?) road, close to the surrounding infrastructure
5. place stairs where needed
6. place shops
shops divide equally along the main roads
shop with short side to the road
shops with related functions locate close to their workshops
no two shops that are the same can go next to each other
how to orient at crossroads?? (not directed to smaller street)
Problems arise with stairs
in the spaces between the placed shops the stairs can not logically be placed
a stair often causes a house to not lay at the street
should shops be clustered?


In [41]:
# Plot a road vertically and horizontally along the canals, as central as possible.
# One row should become all 2's and one column should become all 2's.
# Look for the row and column containing the most 1's.
# Chose the neighbouring row/column that's more central than the other and make the entire index 2.

## Testing playground

In [23]:
# This is a playground for testing small pieces of code.

# Print the grid
for row in grid:
    print(row)

grid_as_list = list(grid)
#grid_as_list
grid[:,13]


[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0])

### 3.1.1 Find row with most water

In [24]:
index = 0

for row in grid:
    print(index, row
    
    )
    index += 1

# function for finding row with maximum 1's
def findMax (grid_as_list):
    row = 0
    j = len_vertical - 1
    for i in range(len_vertical):
        # find left most position of 1 in a row find 1st zero in a row
        while (grid_as_list[i][j] == 1
                     and j >= 0):
            row = i
            j -= 1
         
    print("Row number = ", row,
         ", MaxCount = ", len_vertical - 1 - j)
 
# driver program
findMax(grid_as_list)

0 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
1 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
2 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
3 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
4 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
5 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
6 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
7 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
8 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
9 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
10 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
11 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
12 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
13 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Row number =  4 , MaxCount =  8


### 3.1.2 Find the column with the most water

In [19]:
# Use grid[:,n]?

for grid[:,n] in grid:
    

index = 0

for column in grid:
    print(index, column)
    index += 1

# function for finding row with maximum 1's
def findMax (grid_as_list):
    row = 0
    j = len_vertical - 1
    for i in range(len_vertical):
        # find left most position of 1 in a row find 1st zero in a row
        while (grid_as_list[i][j] == 1
                     and j >= 0):
            row = i
            j -= 1
         
    print("Row number = ", row,
         ", MaxCount = ", len_vertical - 1 - j)
 
# driver program
findMax(grid_as_list)

0 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
1 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
2 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
3 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
4 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
5 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
6 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
7 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
8 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
9 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
10 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
11 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
12 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
13 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Row number =  4 , MaxCount =  8


# Find row and column most central

Row and column most central

In [20]:
# Row and column that are most central
len_vertical = 14
len_horizontal = 24

central_row = int(len_vertical // 2)
central_column = int(len_horizontal // 2)

print("The central row is:", central_row, "The central column is:", central_column)


The central row is: 7 The central column is: 12


# Horizontal road

In [21]:
# Potential rows to put the road in

canal_row = 10

row_above = canal_row -1
row_below = canal_row + 1

potential_roads_horizontal = [row_above, row_below]
print("The potential rows are:", potential_roads_horizontal)

# Pick the right one

def find_nearest(potential_roads_horizontal, central_row):
    array = np.asarray(potential_roads_horizontal)
    idx = (np.abs(array - central_row)).argmin()
    return array[idx]

horizontal_road = find_nearest(potential_roads_horizontal, central_row)
print("The row where the road will be placed is:", horizontal_road)

The potential rows are: [9, 11]
The row where the road will be placed is: 9


# Vertical road

In [22]:
# Potential rows to put the road in

canal_column = 6

column_left = canal_column -1
column_right = canal_column + 1

potential_roads_vertical = [column_left, column_right]
print("The potential rows are:", potential_roads_vertical)

# Pick the right one

def find_nearest(potential_roads_vertical, central_column):
    array = np.asarray(potential_roads_vertical)
    idx = (np.abs(array - central_column)).argmin()
    return array[idx]

vertical_road = find_nearest(potential_roads_vertical, central_column)
print("The column where the road will be placed is:", vertical_road)

The potential rows are: [5, 7]
The column where the road will be placed is: 7


Place it in the grid

In [ ]:
# Replace the entire row and column with 2.

